export const POST_CATEGORY = {
  ADVENTURE: 'ADVENTURE',
  BUSINESS: 'BUSINESS',
  EXPLORATION: 'EXPLORATION',
  CITY_GUIDES: 'CITY_GUIDES',
  COUNTRY_GUIDES: 'COUNTRY_GUIDES',
  ROAD_TRIP: 'ROAD_TRIP',
  BEACH_DESTINATIONS: 'BEACH_DESTINATIONS',
  MOUNTAIN_ADVENTURE: 'MOUNTAIN_ADVENTURE',
  CULTURAL: 'CULTURAL',
  LUXURY: 'LUXURY',
  BACKPACKING: 'BACKPACKING',
  HONEYMOON: 'HONEYMOON',
  HIDDEN_GEMS: 'HIDDEN_GEMS',
} as const;

export const POST_STATUS = {
  ACTIVE: 'ACTIVE',
  DELETED: 'DELETED',
} as const;

export const DISTRICTS = [
  'Barguna',
  'Barisal',
  'Bhola',
  'Jhalokati',
  'Patuakhali',
  'Pirojpur',
  'Bandarban',
  'Brahmanbaria',
  'Chandpur',
  'Chattogram',
  'Comilla',
  "Cox's Bazar",
  'Feni',
  'Khagrachari',
  'Lakshmipur',
  'Noakhali',
  'Rangamati',
  'Dhaka',
  'Faridpur',
  'Gazipur',
  'Gopalganj',
  'Jamalpur',
  'Kishoreganj',
  'Madaripur',
  'Manikganj',
  'Munshiganj',
  'Mymensingh',
  'Narayanganj',
  'Narsingdi',
  'Netrokona',
  'Rajbari',
  'Shariatpur',
  'Sherpur',
  'Tangail',
  'Bagerhat',
  'Chuadanga',
  'Jessore',
  'Jhenaidah',
  'Khulna',
  'Kushtia',
  'Magura',
  'Meherpur',
  'Narail',
  'Satkhira',
  'Bogra',
  'Joypurhat',
  'Naogaon',
  'Natore',
  'Nawabganj',
  'Pabna',
  'Rajshahi',
  'Sirajgonj',
  'Dinajpur',
  'Gaibandha',
  'Kurigram',
  'Lalmonirhat',
  'Nilphamari',
  'Panchagarh',
  'Rangpur',
  'Thakurgaon',
  'Habiganj',
  'Maulvibazar',
  'Sunamganj',
  'Sylhet',
] as const;

export const PostSearchableFields = ['title', 'location', 'city'];

export const noImage =
  'https://t3.ftcdn.net/jpg/05/79/68/24/360_F_579682479_j4jRfx0nl3C8vMrTYVapFnGP8EgNHgfk.jpg';
